import type {
  TestCase,
  Defect,
  TestRun,
  Environment,
  Release,
  TeamMember,
  ActivityItem,
  WorkItem,
} from "./types";

/* Team Members */

export const teamMembers: TeamMember[] = [
  { id: "u1", name: "Hambali Fadib", email: "hambali@nexqa.io", role: "Admin", initials: "HF" },
  { id: "u2", name: "Sarah Chen", email: "sarah@nexqa.io", role: "QA Lead", initials: "SC" },
  { id: "u3", name: "Marcus Rivera", email: "marcus@nexqa.io", role: "QA Engineer", initials: "MR" },
  { id: "u4", name: "Aiko Tanaka", email: "aiko@nexqa.io", role: "QA Engineer", initials: "AT" },
  { id: "u5", name: "David Park", email: "david@nexqa.io", role: "Developer", initials: "DP" },
];

export let testCases: TestCase[] = [
  {
    id: "CLR-TC-001",
    title: "User Login with Valid Credentials",
    description: "Verify that a registered user can successfully log in with valid email and password.",
    module: "Authentication",
    priority: "Critical",
    status: "Approved",
    type: "Functional",
    assignedTo: "Sarah Chen",
    createdBy: "Hambali Fadib",
    createdAt: "2026-05-15T08:00:00Z",
    updatedAt: "2026-06-08T14:30:00Z",
    requirementId: "REQ-AUTH-001",
    tags: ["login", "auth", "smoke"],
    estimatedTime: "5 min",
    steps: [
      { stepNumber: 1, action: "Navigate to the login page", expectedResult: "Login page is displayed with email and password fields", status: "Passed" },
      { stepNumber: 2, action: "Enter valid email address", expectedResult: "Email field accepts the input", status: "Passed" },
      { stepNumber: 3, action: "Enter valid password", expectedResult: "Password field masks the input", status: "Passed" },
      { stepNumber: 4, action: "Click the 'Sign In' button", expectedResult: "User is redirected to the dashboard", status: "Passed" },
    ],
  },
  {
    id: "CLR-TC-002",
    title: "User Login with Invalid Password",
    description: "Verify error handling when user enters an incorrect password.",
    module: "Authentication",
    priority: "High",
    status: "Approved",
    type: "Functional",
    assignedTo: "Sarah Chen",
    createdBy: "Hambali Fadib",
    createdAt: "2026-05-15T09:00:00Z",
    updatedAt: "2026-06-07T10:15:00Z",
    requirementId: "REQ-AUTH-001",
    tags: ["login", "auth", "negative"],
    estimatedTime: "3 min",
    steps: [
      { stepNumber: 1, action: "Navigate to the login page", expectedResult: "Login page is displayed", status: "Passed" },
      { stepNumber: 2, action: "Enter valid email and incorrect password", expectedResult: "Fields accept input", status: "Passed" },
      { stepNumber: 3, action: "Click 'Sign In'", expectedResult: "Error message 'Invalid credentials' is displayed", status: "Failed", actualResult: "Generic 'Something went wrong' error shown" },
    ],
  },
  {
    id: "CLR-TC-003",
    title: "Create New Project from Dashboard",
    description: "Verify a user can create a new project with all required fields.",
    module: "Project Management",
    priority: "High",
    status: "Ready",
    type: "Functional",
    assignedTo: "Marcus Rivera",
    createdBy: "Sarah Chen",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-06-05T16:45:00Z",
    tags: ["project", "create"],
    estimatedTime: "8 min",
    steps: [
      { stepNumber: 1, action: "Click '+ New Project' button on dashboard", expectedResult: "Create Project modal opens", status: "Passed" },
      { stepNumber: 2, action: "Fill in project name and description", expectedResult: "Fields accept text input", status: "Passed" },
      { stepNumber: 3, action: "Select project type and team members", expectedResult: "Dropdowns work correctly", status: "Not Run" },
      { stepNumber: 4, action: "Click 'Create' button", expectedResult: "Project is created and user is redirected to project page", status: "Not Run" },
    ],
  },
  {
    id: "CLR-TC-004",
    title: "Search Test Cases by Module Filter",
    description: "Verify the search functionality filters test cases correctly by module.",
    module: "Test Management",
    priority: "Medium",
    status: "Draft",
    type: "Functional",
    assignedTo: "Aiko Tanaka",
    createdBy: "Marcus Rivera",
    createdAt: "2026-05-25T11:00:00Z",
    updatedAt: "2026-06-04T09:20:00Z",
    tags: ["search", "filter"],
    estimatedTime: "5 min",
    steps: [
      { stepNumber: 1, action: "Navigate to Test Cases page", expectedResult: "Test cases list is displayed", status: "Not Run" },
      { stepNumber: 2, action: "Click on the 'Module' filter dropdown", expectedResult: "Dropdown shows all available modules", status: "Not Run" },
      { stepNumber: 3, action: "Select 'Authentication' module", expectedResult: "Only Authentication test cases are displayed", status: "Not Run" },
    ],
  },
  {
    id: "CLR-TC-005",
    title: "Export Test Results to CSV",
    description: "Verify that test execution results can be exported to CSV format.",
    module: "Reporting",
    priority: "Medium",
    status: "In Review",
    type: "Functional",
    assignedTo: "Aiko Tanaka",
    createdBy: "Sarah Chen",
    createdAt: "2026-05-28T14:00:00Z",
    updatedAt: "2026-06-09T11:30:00Z",
    tags: ["export", "csv", "reporting"],
    estimatedTime: "4 min",
    steps: [
      { stepNumber: 1, action: "Navigate to a completed test run", expectedResult: "Test run detail page is shown", status: "Passed" },
      { stepNumber: 2, action: "Click 'Export' button", expectedResult: "Export options dropdown appears", status: "Passed" },
      { stepNumber: 3, action: "Select 'CSV' format", expectedResult: "CSV file is downloaded with correct data", status: "Blocked" },
    ],
  },
  {
    id: "CLR-TC-006",
    title: "Dashboard KPI Cards Display Correctly",
    description: "Verify all 4 KPI cards on the dashboard show accurate real-time data.",
    module: "Dashboard",
    priority: "High",
    status: "Approved",
    type: "UI",
    assignedTo: "Marcus Rivera",
    createdBy: "Hambali Fadib",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-08T17:00:00Z",
    tags: ["dashboard", "kpi", "ui"],
    estimatedTime: "6 min",
    steps: [
      { stepNumber: 1, action: "Navigate to the main dashboard", expectedResult: "Dashboard loads within 2 seconds", status: "Passed" },
      { stepNumber: 2, action: "Verify Total Test Cases card", expectedResult: "Shows correct count matching DB records", status: "Passed" },
      { stepNumber: 3, action: "Verify Test Execution Rate card", expectedResult: "Shows percentage of executed vs total", status: "Passed" },
      { stepNumber: 4, action: "Verify Defect Density card", expectedResult: "Shows defects per test case ratio", status: "Passed" },
    ],
  },
  {
    id: "CLR-TC-007",
    title: "Defect Severity Badge Color Coding",
    description: "Verify defect severity badges display with correct color coding across all views.",
    module: "Defect Management",
    priority: "Medium",
    status: "Ready",
    type: "UI",
    assignedTo: "Sarah Chen",
    createdBy: "Marcus Rivera",
    createdAt: "2026-06-02T10:00:00Z",
    updatedAt: "2026-06-06T14:00:00Z",
    tags: ["defect", "ui", "badge"],
    estimatedTime: "4 min",
    steps: [
      { stepNumber: 1, action: "Navigate to Defects page", expectedResult: "Defect list is displayed", status: "Not Run" },
      { stepNumber: 2, action: "Check Critical severity badge", expectedResult: "Badge is red with white text", status: "Not Run" },
      { stepNumber: 3, action: "Check High severity badge", expectedResult: "Badge is orange with white text", status: "Not Run" },
      { stepNumber: 4, action: "Check Medium severity badge", expectedResult: "Badge is yellow/amber", status: "Not Run" },
      { stepNumber: 5, action: "Check Low severity badge", expectedResult: "Badge is gray", status: "Not Run" },
    ],
  },
  {
    id: "CLR-TC-008",
    title: "API Response Time Under Load",
    description: "Verify API response time stays under 500ms with 50 concurrent users.",
    module: "Performance",
    priority: "High",
    status: "Approved",
    type: "Performance",
    assignedTo: "David Park",
    createdBy: "Hambali Fadib",
    createdAt: "2026-06-03T09:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
    tags: ["api", "performance", "load"],
    estimatedTime: "15 min",
    steps: [
      { stepNumber: 1, action: "Set up load testing tool with 50 virtual users", expectedResult: "Tool is configured and ready", status: "Passed" },
      { stepNumber: 2, action: "Execute GET /api/test-cases endpoint", expectedResult: "All responses return 200 OK", status: "Passed" },
      { stepNumber: 3, action: "Check 95th percentile response time", expectedResult: "Response time is under 500ms", status: "Failed", actualResult: "P95 response time was 782ms" },
    ],
  },
  {
    id: "CLR-TC-009",
    title: "Mobile Responsive Layout - Test Cases Page",
    description: "Verify test cases page renders correctly on mobile viewport (375px).",
    module: "Responsive Design",
    priority: "Medium",
    status: "Draft",
    type: "UI",
    assignedTo: "Aiko Tanaka",
    createdBy: "Sarah Chen",
    createdAt: "2026-06-05T12:00:00Z",
    updatedAt: "2026-06-07T15:30:00Z",
    tags: ["mobile", "responsive", "ui"],
    estimatedTime: "7 min",
    steps: [
      { stepNumber: 1, action: "Open test cases page in 375px viewport", expectedResult: "Sidebar collapses to hamburger menu", status: "Not Run" },
      { stepNumber: 2, action: "Tap hamburger menu icon", expectedResult: "Sidebar slides in as overlay", status: "Not Run" },
      { stepNumber: 3, action: "Scroll through test case list", expectedResult: "Table scrolls horizontally with sticky first column", status: "Not Run" },
    ],
  },
  {
    id: "CLR-TC-010",
    title: "Bulk Delete Test Cases",
    description: "Verify multiple test cases can be selected and deleted in bulk.",
    module: "Test Management",
    priority: "Low",
    status: "In Review",
    type: "Functional",
    assignedTo: "Marcus Rivera",
    createdBy: "Aiko Tanaka",
    createdAt: "2026-06-06T14:00:00Z",
    updatedAt: "2026-06-09T16:00:00Z",
    tags: ["bulk", "delete", "management"],
    estimatedTime: "5 min",
    steps: [
      { stepNumber: 1, action: "Select multiple test cases using checkboxes", expectedResult: "Selection counter shows selected count", status: "Not Run" },
      { stepNumber: 2, action: "Click 'Delete Selected' button", expectedResult: "Confirmation dialog appears", status: "Not Run" },
      { stepNumber: 3, action: "Confirm deletion", expectedResult: "Selected test cases are removed from the list", status: "Not Run" },
    ],
  },
  {
    id: "CLR-TC-011",
    title: "Session Timeout After Inactivity",
    description: "Verify the application redirects to login after 30 minutes of inactivity.",
    module: "Authentication",
    priority: "High",
    status: "Approved",
    type: "Security",
    assignedTo: "David Park",
    createdBy: "Hambali Fadib",
    createdAt: "2026-06-07T08:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
    tags: ["security", "session", "timeout"],
    estimatedTime: "35 min",
    steps: [
      { stepNumber: 1, action: "Log in and remain idle for 30 minutes", expectedResult: "Session expires and user sees timeout notification", status: "Passed" },
      { stepNumber: 2, action: "Attempt to interact with the page", expectedResult: "User is redirected to login page", status: "Passed" },
    ],
  },
  {
    id: "CLR-TC-012",
    title: "Release Notes Generation",
    description: "Verify release notes can be auto-generated from completed test runs and resolved defects.",
    module: "Release Management",
    priority: "Medium",
    status: "Draft",
    type: "Functional",
    assignedTo: "Aiko Tanaka",
    createdBy: "Sarah Chen",
    createdAt: "2026-06-08T11:00:00Z",
    updatedAt: "2026-06-09T14:00:00Z",
    tags: ["release", "notes", "generation"],
    estimatedTime: "10 min",
    steps: [
      { stepNumber: 1, action: "Navigate to Releases page", expectedResult: "Releases list is shown", status: "Not Run" },
      { stepNumber: 2, action: "Select a release and click 'Generate Notes'", expectedResult: "Modal with auto-generated notes appears", status: "Not Run" },
      { stepNumber: 3, action: "Review and edit generated notes", expectedResult: "Notes are editable with markdown support", status: "Not Run" },
    ],
  },
];

/* Defects */

export const defects: Defect[] = [
  {
    id: "CLR-DEF-001",
    title: "Login form not validating empty email field",
    description: "The login form submits even when the email field is empty, causing a 500 error from the API.",
    severity: "High",
    status: "Open",
    type: "Bug",
    priority: "High",
    assignedTo: "David Park",
    reportedBy: "Sarah Chen",
    linkedTestCase: "CLR-TC-001",
    linkedTestRun: "Sprint 3 Regression",
    environment: "Staging",
    browser: "Chrome 126",
    stepsToReproduce: "1. Navigate to login page\n2. Leave email field empty\n3. Enter any password\n4. Click Sign In\n5. Observe 500 Internal Server Error",
    createdAt: "2026-06-08T09:30:00Z",
    updatedAt: "2026-06-09T14:00:00Z",
    tags: ["login", "validation", "api"],
  },
  {
    id: "CLR-DEF-002",
    title: "Dashboard KPI card shows NaN for new projects",
    description: "When a project has zero test cases, the Test Execution Rate KPI card displays NaN% instead of 0%.",
    severity: "Medium",
    status: "In Progress",
    type: "Bug",
    priority: "Medium",
    assignedTo: "David Park",
    reportedBy: "Marcus Rivera",
    linkedTestCase: "CLR-TC-006",
    environment: "Development",
    browser: "Firefox 127",
    createdAt: "2026-06-07T15:20:00Z",
    updatedAt: "2026-06-09T11:00:00Z",
    tags: ["dashboard", "kpi", "division-by-zero"],
  },
  {
    id: "CLR-DEF-003",
    title: "Generic error message on invalid login credentials",
    description: "The login page shows 'Something went wrong' instead of 'Invalid credentials' when wrong password is entered.",
    severity: "High",
    status: "Open",
    type: "Bug",
    priority: "High",
    assignedTo: "David Park",
    reportedBy: "Sarah Chen",
    linkedTestCase: "CLR-TC-002",
    linkedTestRun: "Sprint 3 Regression",
    environment: "Staging",
    browser: "Chrome 126",
    createdAt: "2026-06-08T10:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
    tags: ["login", "error-handling", "ux"],
  },
  {
    id: "CLR-DEF-004",
    title: "CSV export fails for large datasets",
    description: "Exporting test results with more than 1000 rows causes a browser timeout.",
    severity: "High",
    status: "Blocked",
    type: "Bug",
    priority: "High",
    assignedTo: "David Park",
    reportedBy: "Aiko Tanaka",
    linkedTestCase: "CLR-TC-005",
    environment: "Production",
    browser: "Chrome 126, Safari 18",
    createdAt: "2026-06-06T14:00:00Z",
    updatedAt: "2026-06-09T09:00:00Z",
    tags: ["export", "performance", "csv"],
  },
  {
    id: "CLR-DEF-005",
    title: "API P95 latency exceeds 500ms threshold",
    description: "Under load testing with 50 concurrent users, the GET /api/test-cases endpoint has P95 latency of 782ms.",
    severity: "Critical",
    status: "Open",
    type: "Bug",
    priority: "Critical",
    assignedTo: "David Park",
    reportedBy: "Hambali Fadib",
    linkedTestCase: "CLR-TC-008",
    environment: "Staging",
    stepsToReproduce: "1. Set up k6 with 50 VUs\n2. Target GET /api/test-cases\n3. Run for 5 minutes\n4. Check P95 metric",
    createdAt: "2026-06-09T08:30:00Z",
    updatedAt: "2026-06-09T16:00:00Z",
    tags: ["api", "performance", "critical"],
  },
  {
    id: "CLR-DEF-006",
    title: "Sidebar nav item stays active after page change",
    description: "When navigating from Test Cases to Defects, the Test Cases nav item remains highlighted.",
    severity: "Low",
    status: "Resolved",
    type: "Bug",
    priority: "Low",
    assignedTo: "Marcus Rivera",
    reportedBy: "Aiko Tanaka",
    environment: "Development",
    browser: "Chrome 126",
    createdAt: "2026-06-05T11:00:00Z",
    updatedAt: "2026-06-08T16:00:00Z",
    resolvedAt: "2026-06-08T16:00:00Z",
    tags: ["ui", "navigation", "sidebar"],
  },
  {
    id: "CLR-DEF-007",
    title: "Test step status not persisting after page reload",
    description: "When executing a test run and setting step statuses to Passed/Failed, the statuses reset to Not Run after refreshing.",
    severity: "High",
    status: "Open",
    type: "Bug",
    priority: "High",
    assignedTo: "David Park",
    reportedBy: "Sarah Chen",
    linkedTestCase: "CLR-TC-001",
    linkedTestRun: "Debug Test Run",
    environment: "Development",
    browser: "Chrome 126",
    createdAt: "2026-06-04T10:00:00Z",
    updatedAt: "2026-06-09T12:00:00Z",
    tags: ["test-execution", "persistence"],
  },
  {
    id: "CLR-DEF-008",
    title: "Missing tooltip on disabled navigation items",
    description: "Disabled nav items (Requirement, Test Runs) don't show 'Coming soon' tooltip on hover.",
    severity: "Low",
    status: "Closed",
    type: "Enhancement",
    priority: "Low",
    assignedTo: "Marcus Rivera",
    reportedBy: "Hambali Fadib",
    environment: "Development",
    createdAt: "2026-06-03T09:00:00Z",
    updatedAt: "2026-06-06T10:00:00Z",
    resolvedAt: "2026-06-06T10:00:00Z",
    tags: ["ui", "tooltip", "accessibility"],
  },
  {
    id: "CLR-DEF-009",
    title: "Date picker does not respect user timezone",
    description: "Release target dates are saved in UTC but displayed without timezone conversion, causing off-by-one day errors.",
    severity: "Medium",
    status: "Open",
    type: "Bug",
    priority: "Medium",
    assignedTo: "David Park",
    reportedBy: "Marcus Rivera",
    environment: "Production",
    browser: "All browsers",
    createdAt: "2026-06-07T08:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
    tags: ["date", "timezone", "ux"],
  },
  {
    id: "CLR-DEF-010",
    title: "Notification badge count not updating in real-time",
    description: "The notification bell badge count only updates on page refresh, not when new events occur.",
    severity: "Medium",
    status: "In Progress",
    type: "Enhancement",
    priority: "Medium",
    assignedTo: "Marcus Rivera",
    reportedBy: "Sarah Chen",
    environment: "Development",
    createdAt: "2026-06-08T14:00:00Z",
    updatedAt: "2026-06-09T15:00:00Z",
    tags: ["notification", "real-time", "websocket"],
  },
  {
    id: "CLR-DEF-011",
    title: "Bulk select checkbox alignment broken on Safari",
    description: "The checkbox column in the test cases table is misaligned on Safari 18, overlapping with the ID column.",
    severity: "Low",
    status: "Open",
    type: "Bug",
    priority: "Low",
    assignedTo: "Aiko Tanaka",
    reportedBy: "Marcus Rivera",
    environment: "Development",
    browser: "Safari 18",
    createdAt: "2026-06-09T10:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
    tags: ["ui", "safari", "css"],
  },
  {
    id: "CLR-DEF-012",
    title: "Scrollbar flickers on Test Steps table resize",
    description: "When resizing the browser window while viewing test steps, the custom scrollbar flickers rapidly.",
    severity: "Low",
    status: "Resolved",
    type: "Bug",
    priority: "Low",
    assignedTo: "Aiko Tanaka",
    reportedBy: "Sarah Chen",
    environment: "Development",
    browser: "Chrome 126",
    createdAt: "2026-06-05T15:00:00Z",
    updatedAt: "2026-06-07T11:00:00Z",
    resolvedAt: "2026-06-07T11:00:00Z",
    tags: ["ui", "scrollbar", "css"],
  },
  {
    id: "CLR-DEF-013",
    title: "Empty state missing on new project defects page",
    description: "When a project has no defects, the page shows a blank white area instead of an empty state illustration.",
    severity: "Medium",
    status: "Open",
    type: "Enhancement",
    priority: "Medium",
    assignedTo: "Aiko Tanaka",
    reportedBy: "Hambali Fadib",
    environment: "Development",
    createdAt: "2026-06-09T07:00:00Z",
    updatedAt: "2026-06-09T07:00:00Z",
    tags: ["ui", "empty-state", "ux"],
  },
  {
    id: "CLR-DEF-014",
    title: "Release progress bar doesn't account for skipped tests",
    description: "The release readiness progress bar only counts passed/failed tests, ignoring skipped tests which inflates the pass rate.",
    severity: "High",
    status: "Open",
    type: "Bug",
    priority: "High",
    assignedTo: "David Park",
    reportedBy: "Sarah Chen",
    linkedTestRun: "Sprint 3 Regression",
    environment: "Staging",
    createdAt: "2026-06-08T16:00:00Z",
    updatedAt: "2026-06-09T12:00:00Z",
    tags: ["release", "progress", "calculation"],
  },
  {
    id: "CLR-DEF-015",
    title: "Dark mode toggle causes layout shift",
    description: "When toggling dark mode, the sidebar briefly collapses then re-expands causing a visual glitch.",
    severity: "Low",
    status: "Closed",
    type: "Bug",
    priority: "Low",
    assignedTo: "Marcus Rivera",
    reportedBy: "Aiko Tanaka",
    environment: "Development",
    browser: "Chrome 126",
    createdAt: "2026-06-02T12:00:00Z",
    updatedAt: "2026-06-04T09:00:00Z",
    resolvedAt: "2026-06-04T09:00:00Z",
    tags: ["dark-mode", "layout", "css"],
  },
];

/* Test Runs */

export const testRuns: TestRun[] = [
  {
    id: "CLR-TR-001",
    name: "Sprint 3 Regression",
    description: "Full regression test suite for Sprint 3 release candidate.",
    status: "In Progress",
    environment: "Staging",
    release: "v1.2.0",
    assignedTo: "Sarah Chen",
    totalCases: 45,
    passed: 28,
    failed: 5,
    blocked: 3,
    notRun: 9,
    startedAt: "2026-06-08T08:00:00Z",
    createdAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "CLR-TR-002",
    name: "Debug Test Run",
    description: "Quick verification of critical authentication fixes.",
    status: "Completed",
    environment: "Development",
    assignedTo: "Marcus Rivera",
    totalCases: 8,
    passed: 5,
    failed: 2,
    blocked: 1,
    notRun: 0,
    startedAt: "2026-06-06T14:00:00Z",
    completedAt: "2026-06-06T16:30:00Z",
    createdAt: "2026-06-06T13:00:00Z",
  },
  {
    id: "CLR-TR-003",
    name: "Smoke Test - Production Deploy",
    description: "Critical path smoke tests after v1.1.0 production deployment.",
    status: "Completed",
    environment: "Production",
    release: "v1.1.0",
    assignedTo: "Hambali Fadib",
    totalCases: 12,
    passed: 12,
    failed: 0,
    blocked: 0,
    notRun: 0,
    startedAt: "2026-06-01T20:00:00Z",
    completedAt: "2026-06-01T21:00:00Z",
    createdAt: "2026-06-01T19:00:00Z",
  },
];

/* Environments */

export const environments: Environment[] = [
  {
    id: "env-1",
    name: "Local Development",
    url: "http://localhost:3000",
    type: "Development",
    status: "Active",
    version: "0.1.0-dev",
    description: "Local development environment for individual sandbox branches.",
  },
  {
    id: "env-2",
    name: "Staging",
    url: "https://staging.nexqa.io",
    type: "Staging",
    status: "Active",
    lastDeployed: "2026-06-09T14:00:00Z",
    version: "v1.2.0-rc.1",
    description: "Pre-production environment for integration testing and QA validation.",
  },
  {
    id: "env-3",
    name: "Production",
    url: "https://clarity-verification-platform-web.vercel.app",
    type: "Production",
    status: "Active",
    lastDeployed: "2026-06-01T20:00:00Z",
    version: "v1.1.0",
    description: "Live production environment. Deployed from main branch via Vercel.",
  },
  {
    id: "env-4",
    name: "QA Environment",
    url: "https://qa.nexqa.io",
    type: "QA",
    status: "Maintenance",
    lastDeployed: "2026-06-05T10:00:00Z",
    version: "v1.1.1-hotfix",
    description: "Dedicated QA environment for automated test suite execution.",
  },
];

/* Releases */

export const releases: Release[] = [
  {
    id: "rel-1",
    version: "v1.0.0",
    name: "Foundation Launch",
    status: "Released",
    startDate: "2026-04-01",
    targetDate: "2026-05-15",
    releaseDate: "2026-05-15",
    description: "Initial platform launch with core TCMS and user management.",
    totalTestCases: 30,
    passedTestCases: 30,
    totalDefects: 8,
    openDefects: 0,
    criticalDefects: 0,
  },
  {
    id: "rel-2",
    version: "v1.1.0",
    name: "Defect Management",
    status: "Released",
    startDate: "2026-05-16",
    targetDate: "2026-06-01",
    releaseDate: "2026-06-01",
    description: "Added defect tracking, linking to test cases, and severity management.",
    totalTestCases: 25,
    passedTestCases: 24,
    totalDefects: 5,
    openDefects: 0,
    criticalDefects: 0,
  },
  {
    id: "rel-3",
    version: "v1.2.0",
    name: "Sprint 3 - Dashboard & Analytics",
    status: "In Progress",
    startDate: "2026-06-02",
    targetDate: "2026-06-20",
    description: "Dashboard KPIs, test execution analytics, CSV export, and performance improvements.",
    totalTestCases: 45,
    passedTestCases: 28,
    totalDefects: 12,
    openDefects: 7,
    criticalDefects: 1,
  },
  {
    id: "rel-4",
    version: "v1.3.0",
    name: "Collaboration & Notifications",
    status: "Planning",
    startDate: "2026-06-21",
    targetDate: "2026-07-15",
    description: "Real-time notifications, team collaboration features, and comment threads.",
    totalTestCases: 0,
    passedTestCases: 0,
    totalDefects: 0,
    openDefects: 0,
    criticalDefects: 0,
  },
];

/* Activity Feed */

export const activityFeed: ActivityItem[] = [
  { id: "act-1", user: "Hambali Fadib", userInitials: "HF", action: "reported", targetType: "defect", targetId: "CLR-DEF-005", targetTitle: "API P95 latency exceeds 500ms", timestamp: "2026-06-09T08:30:00Z" },
  { id: "act-2", user: "Sarah Chen", userInitials: "SC", action: "resolved", targetType: "defect", targetId: "CLR-DEF-006", targetTitle: "Sidebar nav active state bug", timestamp: "2026-06-08T16:00:00Z" },
  { id: "act-3", user: "Marcus Rivera", userInitials: "MR", action: "executed", targetType: "test-run", targetId: "CLR-TR-001", targetTitle: "Sprint 3 Regression", timestamp: "2026-06-08T08:00:00Z" },
  { id: "act-4", user: "Aiko Tanaka", userInitials: "AT", action: "created", targetType: "test-case", targetId: "CLR-TC-012", targetTitle: "Release Notes Generation", timestamp: "2026-06-08T11:00:00Z" },
  { id: "act-5", user: "David Park", userInitials: "DP", action: "commented", targetType: "defect", targetId: "CLR-DEF-004", targetTitle: "CSV export timeout", timestamp: "2026-06-09T09:00:00Z", detail: "Investigating server-side streaming approach for large exports." },
  { id: "act-6", user: "Sarah Chen", userInitials: "SC", action: "updated", targetType: "test-case", targetId: "CLR-TC-005", targetTitle: "Export Test Results to CSV", timestamp: "2026-06-09T11:30:00Z" },
  { id: "act-7", user: "Hambali Fadib", userInitials: "HF", action: "closed", targetType: "defect", targetId: "CLR-DEF-015", targetTitle: "Dark mode layout shift", timestamp: "2026-06-04T09:00:00Z" },
  { id: "act-8", user: "Marcus Rivera", userInitials: "MR", action: "assigned", targetType: "defect", targetId: "CLR-DEF-010", targetTitle: "Notification badge not updating", timestamp: "2026-06-08T14:30:00Z" },
];

/* Work Items (Kanban) */

export const workItems: WorkItem[] = [
  { id: "wi-1", title: "Database Schema Design", type: "Task", status: "To Do", priority: "High", progress: 0, scope: "ENERGY / Migration", assignedTo: "Hambali Fadib", dueIn: "10d remaining", createdAt: "2026-06-05T08:00:00Z" },
  { id: "wi-2", title: "SP Load Data Migration", type: "Task", status: "In Progress", priority: "High", progress: 50, scope: "ENERGY / Migration", assignedTo: "Hambali Fadib", dueIn: "10d remaining", createdAt: "2026-06-03T08:00:00Z" },
  { id: "wi-3", title: "API Integration Fix", type: "Task", status: "In Progress", priority: "Medium", progress: 30, scope: "DEVELOPMENT / API", assignedTo: "Hambali Fadib", createdAt: "2026-06-04T10:00:00Z" },
  { id: "wi-4", title: "Security Audit Report", type: "Task", status: "Blocked", priority: "High", progress: 65, scope: "ENERGY / Migration", assignedTo: "Hambali Fadib", dueIn: "10d remaining", createdAt: "2026-06-02T09:00:00Z" },
  { id: "wi-5", title: "User Interface Prototyping", type: "Task", status: "Completed", priority: "Medium", progress: 100, scope: "ENERGY / Migration", assignedTo: "Hambali Fadib", createdAt: "2026-06-01T08:00:00Z" },
];

export function addTestCase(tc: TestCase) {
  testCases.push(tc);
}

export function generateTestCaseId(): string {
  const ids = testCases.map((tc) => {
    const match = tc.id.match(/CLR-TC-(\d+)/);
    return match ? parseInt(match[1], 10) : 0;
  });
  const maxId = ids.length > 0 ? Math.max(...ids) : 0;
  const nextId = maxId + 1;
  return `CLR-TC-${String(nextId).padStart(3, "0")}`;
}

export function getModules(): string[] {
  const modules = testCases.map((tc) => tc.module);
  return Array.from(new Set(modules)).sort();
}
