from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '20afdcc234c2'
down_revision: Union[str, None] = '20260614_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('test_case_id', sa.Uuid(), nullable=True))
    op.add_column('defects', sa.Column('test_run_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_defects_linked_test_case'), table_name='defects')
    op.create_index(op.f('ix_defects_test_case_id'), 'defects', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_defects_test_run_id'), 'defects', ['test_run_id'], unique=False)
    op.create_foreign_key(None, 'defects', 'test_runs', ['test_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'defects', 'test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
    op.drop_column('defects', 'linked_test_run')
    op.drop_column('defects', 'linked_test_case')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('linked_test_case', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('defects', sa.Column('linked_test_run', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.drop_index(op.f('ix_defects_test_run_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_test_case_id'), table_name='defects')
    op.create_index(op.f('ix_defects_linked_test_case'), 'defects', ['linked_test_case'], unique=False)
    op.drop_column('defects', 'test_run_id')
    op.drop_column('defects', 'test_case_id')
    # ### end Alembic commands ###

