from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a06b2afe2a32'
down_revision: Union[str, None] = '69d473bf5279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('test_case_id', sa.Uuid(), nullable=True))
    op.add_column('work_items', sa.Column('defect_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_work_items_defect_id_defects', 'work_items', 'defects', ['defect_id'], ['id'])
    op.create_foreign_key('fk_work_items_test_case_id_test_cases', 'work_items', 'test_cases', ['test_case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_work_items_test_case_id_test_cases', 'work_items', type_='foreignkey')
    op.drop_constraint('fk_work_items_defect_id_defects', 'work_items', type_='foreignkey')
    op.drop_column('work_items', 'defect_id')
    op.drop_column('work_items', 'test_case_id')
    # ### end Alembic commands ###

